### DISCUSSION TITLE
Help with TOML

### DISCUSSION THREAD

**Discussion by ghost** [TomWright/dasel#114] [Q&A] [answered]
Hello @TomWright,

Can you give me any help with the following TOML file? I need to create it with dasel, but I am stuck how to achieve this example below

```
[[servers]]
host = "127.0.0.1"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "cn=admin,dc=grafana,dc=org"
bind_password = 'grafana'
search_filter = "(cn=%s)"
search_base_dns = ["dc=grafana,dc=org"]

[servers.attributes]
member_of = "memberOf"
email =  "email"
```
Thanks again!

**Comment by ghost** [comment]
Hello @TomWright,

The question is for the double bracket at the top and the search_base_dns, which starts with a bracket and ends with a bracket. Thanks!

**Reply by TomWright** [reply]
I'm out at the moment but will help out in a little while.

**Reply by ghost** [reply]
No hurry, thanks!

**Comment by TomWright** [comment, marked as answer]
In TOML the `[[servers]]` tag is just appending an object to an array of objects.
This can be achieved with the `[]` selector:
```
dasel put object -p toml -t string '.servers.[]' 'host=127.0.0.1'
```

You can then add the attributes to all server objects with this (notice the `-m` and `[*]` targetting all servers items):
```
dasel put object -p toml -t string -t string -m '.servers.[*].attributes' member_of=memberOf email=email
```

Search_base_dns starts and ends with square brackets, meaning it is an array. You can create an array in dasel by using the `[0]` selector which targets the first element in an array:
```
dasel put string -p toml -m '.servers.[*].search_base_dns.[0]' dc=grafana,dc=org
```

Example:
```
echo '' | 
dasel put object -p toml -t string -t int -t bool -t bool -t bool -t string -t string -t string '.servers.[]' 'host=127.0.0.1' 'port=389' 'use_ssl=false' 'start_tls=false' 'ssl_skip_verify=false' 'bind_dn=cn=admin,dc=grafana,dc=org' 'bind_password=grafana' 'search_filter=(cn=%s)' | 
dasel put object -p toml -t string -t string -m '.servers.[*].attributes' member_of=memberOf email=email | 
dasel put string -p toml -m '.servers.[*].search_base_dns.[0]' dc=grafana,dc=org
```
```toml
[[servers]]
  bind_dn = "cn=admin,dc=grafana,dc=org"
  bind_password = "grafana"
  host = "127.0.0.1"
  port = 389
  search_base_dns = ["dc=grafana,dc=org"]
  search_filter = "(cn=%s)"
  ssl_skip_verify = false
  start_tls = false
  use_ssl = false

  [servers.attributes]
    email = "email"
    member_of = "memberOf"
```

**Comment by ghost** [comment]
Thanks, I will look at it tonight or later this week!

**Comment by ghost** [comment]
Hello @TomWright,

Still some struggeling, especially with the second and third [[ ]]. This is the final toml we do need.

Could you please take a look at it?

```
[[servers]]
bind_dn = 'CN=var.ad_read_user,OU=ServiceAccount,OU=xxxxx,OU=xxxxxxxx,DC=DOMAIN_OU1,DC=DOMAIN_OU2'
bind_password = ad_read_user_password
group_search_base_dns = ['dc=DOMAIN_OU1,dc=DOMAIN_OU2']
host = dc01.domain.com
port = 636
search_base_dns = ['dc=DOMAIN_OU1,dc=DOMAIN_OU2']
search_filter = '(|(sAMAccountName=%s)(userPrincipalName=%s))'
ssl_skip_verify = true
start_tls = false
use_ssl = true

[servers.attributes]
name = 'givenName'
surname = 'sn'
username = 'cn'
member_of = 'memberOf'
email =  'email'

[[servers.group_mappings]]
group_dn = 'CN=xxxxx,OU=Groups,OU=xxxxxxxx,OU=xxxxxxxx,DC=DOMAIN_OU1,DC=DOMAIN_OU2'
org_role = 'Admin'
grafana_admin = true

[[servers.group_mappings]]
group_dn = 'CN=xxxxx,OU=Groups,OU=xxxxxxxx,OU=xxxxxxxx,DC=DOMAIN_OU1,DC=DOMAIN_OU2'
org_role = 'Viewer'
```
Thanks again.

**Reply by TomWright** [reply]
You can just follow the same logic I outlined before. `[[x]]` just appends the following object to an array called "x".

```bash
echo '' |
./dasel put object -p toml -t string '.servers.[]' 'bind_dn=x' |
./dasel put object -p toml -m -t string '.servers.[*].attributes' 'name=y' |
./dasel put object -p toml -m -t string '.servers.[*].group_mappings.[]' 'group_dn=a' |
./dasel put object -p toml -m -t string '.servers.[*].group_mappings.[]' 'group_dn=b'
```

```toml
[[servers]]
  bind_dn = "x"

  [servers.attributes]
    name = "y"

  [[servers.group_mappings]]
    group_dn = "a"

  [[servers.group_mappings]]
    group_dn = "b"
```
