### DISCUSSION TITLE
yaml selector help

### DISCUSSION THREAD

**Discussion by mark05e** [TomWright/dasel#142] [Q&A] [answered]
I have a yaml file which looks like this. How do I select any elements in this example? I feel that since there is no root it might not be possible?

```yaml
---
- id: run1
  execute-command: "C:\\_dev\\webhook-demo\\run1.cmd"
  command-working-directory: "C:\\_dev\\webhook-demo\\"
- id: start
  execute-command: "C:\\_dev\\webhook-demo\\start.cmd"
  include-command-output-in-response: true
- id: queryuser
  execute-command: "C:\\_dev\\webhook-demo\\query_user.cmd"
  include-command-output-in-response: true
- id: queryprocess
  execute-command: "C:\\_dev\\webhook-demo\\query_process.cmd"
  include-command-output-in-response: true
```

stuff I tried that did not work

```
dasel_windows_amd64.exe -f hooks.yml -s '---.id'
dasel_windows_amd64.exe -f hooks.yml -s '.id' -m
dasel_windows_amd64.exe -f hooks.yml -s '[*].id' -m
```

# Solution
Try using double quotes or no quotes.

ref: https://github.com/TomWright/dasel/discussions/142#discussioncomment-803932
