### DISCUSSION TITLE
Can't create the type of YAML list I want

### DISCUSSION THREAD

**Discussion by paradajz** [TomWright/dasel#185] [Q&A] [answered]
How would I generate something like this with dasel? Note: I don't know how is this called but GitLab tell me it expects "an array of hashes".

```
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always
```

I ended up with this, which is not correct:

```
  rules:
  - 'if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME && $CI_OPEN_MERGE_REQUESTS'
  - 'when: never'
  - 'when: always'
```

Command used:

```
        {
            echo "" |
            dasel put string -p yaml -m "rules.[]" 'if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME && $CI_OPEN_MERGE_REQUESTS' |
            dasel put string -p yaml -m "rules.[]" "when: never" |
            dasel put string -p yaml -m "rules.[]" "when: always"
        } >> out
```

**Comment by TomWright** [comment, marked as answer]
Hey @paradaj, sorry for the delayed response. I must have missed this when it was first posted.

This is how you can achieve that:
```bash
echo "" |
dasel put string -p yaml 'rules.[].if' 'if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME && $CI_OPEN_MERGE_REQUESTS' |
dasel put string -p yaml -m "rules.[0].when" "never" |
dasel put string -p yaml -m "rules.[].when" "always"
```

The output is:
```yaml
rules:
- if: 'if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME && $CI_OPEN_MERGE_REQUESTS'
  when: never
- when: always
```
