### DISCUSSION TITLE
Support for TOML tables?

### DISCUSSION THREAD

**Discussion by lildata** [TomWright/dasel#195] [Q&A] [answered]
Hi,
Is there a way to handle TOML table (https://toml.io/en/v1.0.0#table)?
Meaning generating & querying something like this:
```toml
[a.b.c]
key1 = "some string"
key2 = 123

[a.b.d]
key1 = "another string"
key2 = 456
```
Many thanks !
