### DISCUSSION TITLE
yaml multi document markers

### DISCUSSION THREAD

**Discussion by electriquo** [TomWright/dasel#237] [Q&A] [answered]
How to select specific YAML [document markers](https://yaml.org/spec/1.2.2/#912-document-markers)?

For example,

```yaml
---
foo: bar
---
foo: baz
---
foo: spam
```

How to tell `dasel` to select the second `foo`?

**Comment by TomWright** [comment, marked as answer]
When reading multiple documents dasel stores them internally as a list, allowing you to access them as follows:
```bash
$ echo '---
foo: bar
---
foo: baz
---
foo: spam' | dasel -r yaml '.[1].foo'
baz
```

**Reply by electriquo** [reply]
Maybe it worth to document it around https://daseldocs.tomwright.me/selectors/all-indexes

**Reply by electriquo** [reply]
Assume the document are differentiated with an anchor key, such as `doc`.
How can `dasel` select a specific document given the `doc` value.

For example, having the following YAML

```yaml
doc: 1
foo: bar
---
doc: 3
foo: baz
---
doc: 2
foo: spam
```

How can `dasel` select the document where `doc` equals `3` and return

```yaml
doc: 3
foo: baz
```
