### DISCUSSION TITLE
Help requested

### DISCUSSION THREAD

**Discussion by Evantage-WS** [TomWright/dasel#244] [Q&A] [answered]
Hi Tom,

I have a question about the yaml below:

```
options:
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
      - arg: --kube-apiserver-arg=feature-gates=HPAContainerMetrics=true
        nodeFilters:
          - server:*
```

I want to add a third -arg, but I am lost, could you be of assistance? Thanks

**Comment by Evantage-WS** [comment]
Anybody? I need this urgently, thanks

**Comment by TomWright** [comment]
An easy way is using the `put document` command: https://dasel.tomwright.me/s/c8557111-a4af-4462-9474-d92659e8ae88

```bash
cat x.yaml | dasel put document -p yaml -d json '.options.k3s.extraArgs.[]' '{"arg": "--x", "a": "b"}'
```

**Reply by Evantage-WS** [reply]
Thanks, but this is not the complete solution to my problem, I especially have a problem getting the "nodeFilters:" and on the next line "-server:*" to work.

```
- arg: --kube-apiserver-arg=feature-gates=HPAContainerMetrics=true
  nodeFilters:
    - server:*
```

Could you give it a try? Thanks again

**Reply by Evantage-WS** [reply]
Could you please also give an example how to delete this entry? I am struggeling with the '--'.

```
- arg: --no-deploy=traefik
  nodeFilters:
   - server:*
```

Thanks

**Reply by Evantage-WS** [reply]
Any help?

**Reply by TomWright** [reply]
Could I get the full input file and expected output please?

**Comment by Evantage-WS** [comment]
Hi,

This is the input:
```
options:
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
      - arg: --kube-apiserver-arg=feature-gates=HPAContainerMetrics=true
        nodeFilters:
          - server:*
```
and I need to delete a part, resulting in:
```
options:
  k3s:
    extraArgs:
      - arg: --kube-apiserver-arg=feature-gates=HPAContainerMetrics=true
        nodeFilters:
          - server:*
```
