### DISCUSSION TITLE
Updated file not saving after a successful put

### DISCUSSION THREAD

**Discussion by joshuadmatthews** [TomWright/dasel#268] [Q&A] [answered]
I am trying to use dasel from a github action

```
      - name: Update my yaml
        working-directory: ${{ github.workspace }}/my/files
        run: |
          dasel put -t string -f config.yaml -s '.some.path' -v myvalue \ 
          dasel -f config.yaml -s '.some.path' 
```

The output of the dasel put shows the correctly updated yaml file, but then the result of the following dasel query returns the original value, and the file does in fact still contain the original value. 

What am I doing wrong here? I tried using a simple string replacement task and that is working fine, so definitely something related to my dasel use case.

```
      - name: Switch flux image automation to target this branch
        uses: Nambers/ReplaceStringInFile@v1.1
        with:
          path:  ${{ github.workspace }}/my/files/config.yaml
          oldString: 'oldval'
          newString: 'newval'
          showFileContent: true
```

this works fine, and the file ends up with the replaced string.
