### DISCUSSION TITLE
Trouble with attribute value selectors in v2

### DISCUSSION THREAD

**Discussion by jaymeedwards** [TomWright/dasel#272] [Q&A] [answered]
Hello,

I've been using dasel in github actions to update the YAML in helm charts.

I was pulling using the latest tag and today got the v2 stuff pulled in.

I've got most of the existing dasel commands working with some tweaks so far, but there's one selector that isn't cooperating:

```
dagster.dagster-user-deployments.deployments.(name=hq-data-ops-dagster-user-code).image.tag
```

This is the v1 syntax. I'm not sure how to do the same with v2.

Anyone able to help?

Thanks in advance.

**Comment by TomWright** [comment, marked as answer]
Hey @eavonius , sorry for the delayed response I've been unwell.

The `(...)` part of your selector was a dynamic selector.

To achieve similar functionality you'll now want to use something like this:
```
dagster.dagster-user-deployments.deployments.filter(equal(name,hq-data-ops-dagster-user-code)).image.tag
```

If you can supply the actual file you're working on I'll be able to give a more precise example.

**Reply by jaymeedwards** [reply]
Sorry to hear you're not feeling well. Hope you get better soon!

Ironically, I pasted the wrong thing when I created this since I was messing around. 

I actually tried exactly what you suggested originally with an error, so I was trying different things.

For now (as a workaround) I've used:

```dagster.dagster-user-deployments.deployments.[0].image.tag```

but it would be nice to be able to explicitly select instead of hardcoding the first array element.

Here's the (excerpted) YAML:

```yaml
dagster:
  dagster-user-deployments:
    deployments:
      - name: "hq-data-ops-dagster-user-code"
        image:
          tag: "2022-08-20-11-27-10"
```

**Reply by TomWright** [reply]
Thanks, I'm feeling a lot better.

No worries, thanks for supplying that example.

Here's a couple of examples:
Find the tag for `hq-data-ops-dagster-user-code`:
```
$ dasel -f f.yaml 'dagster.dagster-user-deployments.deployments.all().filter(equal(name,hq-data-ops-dagster-user-code)).image.tag'
2022-08-20-11-27-10
```

Update the tag for `hq-data-ops-dagster-user-code`:
```
~/tmp/dasel/272 [] $ cat f.yaml
dagster:
  dagster-user-deployments:
    deployments:
      - name: "hq-data-ops-dagster-user-code"
        image:
          tag: "2022-08-20-11-27-10"
      - name: "other"
        image:
          tag: "abc"
~/tmp/dasel/272 [] $ dasel put -f f.yaml -t string -v 'new' 'dagster.dagster-user-deployments.deployments.all().filter(equal(name,hq-data-ops-dagster-user-code)).image.tag'
~/tmp/dasel/272 [] $ cat f.yaml
dagster:
  dagster-user-deployments:
    deployments:
    - image:
        tag: new
      name: hq-data-ops-dagster-user-code
    - image:
        tag: abc
      name: other
```

The main difference is in the way daselv2 iterates through values.

`dagster.dagster-user-deployments.deployments` takes dasel to the deployments item, but it's pointing specifically at that node. To filter the items within it we use `all()` and then `filter()`.

I appreciate this is a difference and may seem a little more verbose, but it should allow users to include much more complicated logic that was hard for me to include in selectors before.
