### DISCUSSION TITLE
Count of elements

### DISCUSSION THREAD

**Discussion by paradajz** [TomWright/dasel#88] [Q&A] [answered]
Hi,

Given a YAML entry like this:

```
  buttons:
    pins:
    -
      port: "C"
      index: 5
    -
      port: "E"
      index: 7
    -
      port: "E"
      index: 9
    - 
      port: "E"
      index: 11
```
using `yq` I can do this to get total number of "pins" like this:

    yq r demo.yml buttons.pins --length

Haven't found anything similar in README - can it be done with dasel?
