### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by rhtenhove** [TomWright/dasel#171]
When trying to select from more complex files, I'm at a loss on what's possible, and keep failing at creating a proper query.

Take the following yaml:

```yaml
---
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
  - - "@semantic-release/git"
    - assets:
        - "tbump.toml"
        - "**/pyproject.toml"
        - "**/setup.py"
        - README.md
      message: |-
        chore(release): ${nextRelease.version}

        ${nextRelease.notes}
```

I would like to retrieve the list under assets. How would I write a query to achieve this?

Some more examples of all the selector features in the documenation would probably help achieve this.

When converted to json, I can get it using `dasel -f .releaserc -r json '.plugins.[3].[1].assets'`, but that would require a consistent ordering, which isn't guaranteed.
