### ISSUE TITLE
Escaping does not work in v2

### ISSUE THREAD

**Issue by genofire** [TomWright/dasel#266]
**Describe the bug**
i like to use an select an key with an dot ( `.`) in it.

**To Reproduce**

1. Create `/host/etc/containerd/config.toml`:

```toml
version = 2
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
  endpoint = ["https://registry-1.docker.io"]
[plugins."io.containerd.grpc.v1.cri"]
  # renovate: datasource=docker depName=k8s.gcr.io/pause versioning=loose
  sandbox_image = "k8s.gcr.io/pause:3.9"
```

2. Run
```bash
cat /host/etc/containerd/config.toml  | ./dasel_linux_amd64 put -r toml '.plugins.io\.containerd\.grpc\.v1\.cri.registry' -t toml -v 'config_path = "/etc/containerd/certs.d"'

```
3. See error:

```toml
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "k8s.gcr.io/pause:3.9"

    [plugins."io.containerd.grpc.v1.cri".containerd]

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true

    [plugins."io.containerd.grpc.v1.cri".registry]

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]

        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]

  [plugins."io\\."]

    [plugins."io\\."."containerd\\."]

      [plugins."io\\."."containerd\\."."grpc\\."]

        [plugins."io\\."."containerd\\."."grpc\\."."v1\\."]

          [plugins."io\\."."containerd\\."."grpc\\."."v1\\.".cri]

            [plugins."io\\."."containerd\\."."grpc\\."."v1\\.".cri.registry]
              config_path = "/etc/containerd/certs.d"
```

**Expected behavior**
behave like in v1-Version, see **Additional context**.

**Desktop (please complete the following information):**

- OS: busybox
- Version: 2

**Additional context**
In old version 1.x this selector works with this command:
```bash
cat /host/etc/containerd/config.toml  | ./dasel_linux_amd64 put document -p toml '.plugins.io\.containerd\.grpc\.v1\.cri.registry' 'config_path = "/etc/containerd/certs.d"'
```

it product following output (like excpacted):
```toml
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "k8s.gcr.io/pause:3.9"

    [plugins."io.containerd.grpc.v1.cri".containerd]

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true

    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"


```
