### ISSUE TITLE
Empty string becoming null when modifying YAML

### ISSUE THREAD

**Issue by blurayne** [TomWright/dasel#400]
I use dasel in a helm filter to modify template for k8s. 

Unfortunately modifying YAML ends in empty string becoming null.

**How to reproduce**

`foo.yaml`:

```yaml
kind: ConfigMap
data:
  foo: hello
  script:
  namespace: myworld
---
kind: xvdcscd
data:
  foo: bar
```

Now modify:

```bash
cat foo.yaml |  dasel put -t string -v "bar" -r yaml -h  'all().filter(equal(kind,ConfigMap)).data.foo'
```

Now watch the value for key `script`

```
kind: ConfigMap
data:
  foo: bar
  script: null
---
kind: xvdcscd
data:
  foo: bar
```

**Version**

Tested on Linux AMD64, dasel version v2.7.0

I just downloaded that release after I encountered the bug with an older release (some weeks old).

**What else?**

If this is standard behavior it would be nyce to add a command-line flag to change this. Dasel is far easier to use then kustomize. Also tools like jq/yq/oq don't help since they cannot parse manifests divided by '---'.
