### ISSUE TITLE
Put string was working under 1.0.4, not under 1.5.1

### ISSUE THREAD

**Issue by ws-way** [TomWright/dasel#41]
Hello @TomWright ,

I do have this yaml:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: mgmt
  name: harbor-exporter
  namespace: registry
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - harbor
  selector:
    matchLabels:
      app: harbor-exporter
```
To change '- harbor' under matchNames I use(d):

```
dasel put string -f $file '.spec.namespaceSelector.matchNames[0]' 'registry'
```
Which gave me the correct result under 1.0.4. Under 1.5.1 the result is like this:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: mgmt
  name: harbor-exporter
  namespace: registry
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - harbor
    matchNames[0]: registry
  selector:
    matchLabels:
      app: harbor-exporter
```
Could you please take a look at this? Thanks.
