### ISSUE TITLE
How do use a map value?

### ISSUE THREAD

**Issue by ws-way** [TomWright/dasel#45]
Hello @TomWright,

I have another question, I do have this code to create the yaml file:

```
echo '' | \
    dasel put string -p yaml 'apiVersion' 'cilium.io/v2' | \
    dasel put string -p yaml 'kind' 'CiliumNetworkPolicy' | \
    dasel put string -p yaml 'metadata.name' 'allow-kube-dns' | \
    dasel put string -p yaml 'spec.endpointSelector.matchLabels' {} | \
    dasel put string -p yaml 'spec.egress.[0].toEndpoints.[0].matchLabels.k8s:io\.kubernetes\.pod\.namespace' 'kube-system' | \
    dasel put string -p yaml 'spec.egress.[0].toEndpoints.[0].matchLabels.k8s-app' 'kube-dns' | \
    dasel put string -p yaml 'spec.egress.[0].toPorts.[0].ports.[0].port' '53' | \
    dasel put string -p yaml 'spec.egress.[0].toPorts.[0].ports.[0].protocol' 'UDP' 
```
This is the output:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-dns
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        k8s-app: kube-dns
        k8s:io.kubernetes.pod.namespace: kube-system
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
  endpointSelector:
    matchLabels: '{}'
```

But when applying this there is an error:
```
error: error validating "tt.yaml": error validating data: ValidationError(CiliumNetworkPolicy.spec.endpointSelector.matchLabels): invalid type for io.cilium.v2.CiliumNetworkPolicy.spec.endpointSelector.matchLabels: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```

When I remove the single quotes arond the {} at matchLabels, it does work. How can I achieve this ?

```
  endpointSelector:
    matchLabels: {}
```

The docs state string, bool or int, but no other options.

Thanks again

**Comment by TomWright** [comment]
This put is causing that entry to appear:
```
dasel put string -p yaml 'spec.endpointSelector.matchLabels' {}
```

Dasel doesn't currently support putting empty values.

I would argue that this item should just be omitted since it doesn't contain any values, giving you the following YAML:
```apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-dns
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        k8s-app: kube-dns
        k8s:io.kubernetes.pod.namespace: kube-system
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
```

**Comment by TomWright** [comment]
Alternatively you could use `dasel put object -p yaml 'spec.endpointSelector.matchLabels'`.

You will currently receive an error stating that `type` is a required flag, but I can remove that requirement.

**Comment by ws-way** [comment]
Hi @TomWright,

Could be great, when possible, to use { } would be great

**Comment by TomWright** [comment]
No worries, that's now supported as of `v1.6.1` 🙂 

Notice that I used `put object` with no types/values rather than `put string {}`:

```
echo '' | \
    dasel put string -p yaml 'apiVersion' 'cilium.io/v2' | \
    dasel put string -p yaml 'kind' 'CiliumNetworkPolicy' | \
    dasel put string -p yaml 'metadata.name' 'allow-kube-dns' | \
    dasel put object -p yaml 'spec.endpointSelector.matchLabels' | \
    dasel put string -p yaml 'spec.egress.[0].toEndpoints.[0].matchLabels.k8s:io\.kubernetes\.pod\.namespace' 'kube-system' | \
    dasel put string -p yaml 'spec.egress.[0].toEndpoints.[0].matchLabels.k8s-app' 'kube-dns' | \
    dasel put string -p yaml 'spec.egress.[0].toPorts.[0].ports.[0].port' '53' | \
    dasel put string -p yaml 'spec.egress.[0].toPorts.[0].ports.[0].protocol' 'UDP' 
```

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-dns
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        k8s-app: kube-dns
        k8s:io.kubernetes.pod.namespace: kube-system
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
  endpointSelector:
    matchLabels: {}
```
