### ISSUE TITLE
Replacing an object's value with new object

### ISSUE THREAD

**Issue by Dentrax** [TomWright/dasel#66]
Thanks for creating such a great tool! I like it very well. 🤙🧡

**Describe the desired outcome**
My question is slightly similar to #23, what I'm trying to achieve is to simply replace the value of a specific object with a new value to be given from by the stdout pipe.

Let's consider we have an `scale.yaml` file:

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: foo-autoscaler
  namespace: foo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foo-deployment
  minReplicas: 40
  maxReplicas: 40
  targetCPUUtilizationPercentage: 70
```

In order to save `spec` object changes from each pipeline run, i should have replace spec object with current values.

**Attempts**

I run this command:

```bash
$ dasel put string -f scale.yml -s "spec" "$(kubectl get hpa foo-autoscaler -o yaml | dasel select -p 'yaml' '.spec')"
```

But I'm getting this one:

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: foo-autoscaler
  namespace: foo
spec: |-
  maxReplicas: 40
  minReplicas: 40
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foo-deployment
  targetCPUUtilizationPercentage: 70
```

Please notice that, I do not want the `|-` [(Block Chomping Indicator)](https://yaml-multiline.info/). But I was expecting for it to set as `object`. I could not find any documentation about replacing the objects in README. It will be cool if you add more examples about replacing - and maybe cross replacing, i.e.: _json object to yaml object_.

Thanks!

**Comment by TomWright** [comment]
Hey @Dentrax,

Thanks for your question.

The docs on replacing objects can be found here: https://github.com/TomWright/dasel#put-object

It doesn't look like dasel can do what you need yet though - you need to define the object property by property.

I think a new `put document` command could help out here.

**Comment by TomWright** [comment]
Additionally the docs on converting between different data formats are here: https://github.com/TomWright/dasel#converting-between-formats

I will soon create a new feature request issue for a `put document` command that should solve your issue.

**Comment by Dentrax** [comment]
Thanks for documentations and prompt response! I guess I missed that parts. :) This will be great feature. I will look forward to it.

What I am concerning about is how to use `put document` in cross formats. i.e.:

**YAML**

```yaml
foo: true
bar: 5
baz:
  qux: false
  quux: "yes"
  quuz: 7
```

**JSON**

```json
[
 {
 "qux": false,
 "quux": "no",
 "quuz": 8
 }
]
```

As we all know, this JSON is in `list of objects` format. If we want to `put document` _any_ JSON object (i.e. first array item) to YAML's `baz`, what command should we execute?

**Comment by TomWright** [comment]
I have created a feature request for this problem: https://github.com/TomWright/dasel/issues/67

For a more specific example in this use-case I would expect something like this:

```
echo 'foo: true
bar: 5
baz:
  qux: false
  quux: "yes"
  quuz: 7' | dasel put document -d json '.baz' $(echo '[
 {
 "qux": false,
 "quux": "no",
 "quuz": 8
 }
]' | dasel -p json '.[0]')
```

## Sudo code explanation with placeholders

`JSON_ARRAY` =
```
[
 {
 "qux": false,
 "quux": "no",
 "quuz": 8
 }
]
```

`YAML_CONTENT` =
```
foo: true
bar: 5
baz:
  qux: false
  quux: "yes"
  quuz: 7
```

The `JSON_ARRAY` isn't actually what we want to use, so we extract the first item from the array.

`JSON_DOCUMENT` = `echo JSON_ARRAY | dasel -p json '.[0]'`
```
{
  "qux": false,
  "quux": "no",
  "quuz": 8
}
```

Finally we put the extracted json document into the yaml content using the baz property.
```
echo YAML_CONTENT | dasel put document -d json '.baz' JSON_DOCUMENT
```
