### ISSUE TITLE
Append to an array of objects not works as expected

### ISSUE THREAD

**Issue by Dentrax** [TomWright/dasel#68]
**Describe the bug**
_Append to an array of objects_ is not working as expected in YAML parser.

**To Reproduce**
1. Go to [Append to an array of objects](https://github.com/TomWright/dasel#append-to-an-array-of-objects-1) section
2. Try the given example:

```bash
echo 'users:
- name: Tom' | dasel put object -p yaml -s '.users[]' -t string name=Frank
users:
- name: Tom
- name: Frank
```

3. I got:

```yaml
users:
- name: Tom
users[]:
  name: Frank
```

**Expected behavior**
```yaml
users:
- name: Tom
- name: Frank
```

**Desktop (please complete the following information):**
 - OS: `macOS`
 - Version: `v1.9.1`

**Additional context**
We can add an unit test case for this scenario during fix phase. :)
